import { Button } from '@chakra-ui/react'
import Head from 'next/head'
import { api } from '../api'
import { Link } from '../components/Link'
import { useUser } from '../hooks/useUser'
import { axiosClient } from '../lib/axios'

export default function Home({ user }: any) {
  // const { user, isLoading, isError, mutate } = useUser({ redirect: false })

  // if (isLoading) {
  //   return (
  //     <h1>Loading</h1>
  //   )
  // }

  const logout = async () => {
    await api.logout()
    location.reload()
  }
  
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home Page</h1>
        <h2>NODE_ENV: {process.env.NODE_ENV}</h2>
        <div>
          {user ?
            <>
              <Link href='/chats'>Chats</Link>
              <Button onClick={logout}>Logout</Button>
            </>
          :
            <>
              <Link href='/signup'>Sign Up</Link> <br />
              <Link href='/signin'>Sign In</Link>
            </>
          }
        </div>
      </main>
    </div>
  )
}

export const getServerSideProps = async () => {
  const user = await api.getUser()
}
