import { Button, useColorMode } from '@chakra-ui/react'
import Head from 'next/head'
import { api } from '@/api'
import { Link } from '@/components/Link'
import { useUser } from '@/hooks/useUser'
import { Loading } from '@/components'

export default function Home() {
  const { user, isLoading, mutate } = useUser({ disableRedirect: true })
  const { toggleColorMode } = useColorMode()

  if (isLoading) {
    return <Loading />
  }

  const logout = async () => {
    await api.logout()
    mutate()
  }
  
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home Page</h1>
        <h2>NODE_ENV: {process.env.NODE_ENV}</h2>
        <div>
          {user ?
            <>
              <Link href='/chats'>Chats</Link>
              <Button onClick={logout}>Logout</Button>
            </>
          :
            <>
              <Link href='/signup'>Sign Up</Link> <br />
              <Link href='/signin'>Sign In</Link>
            </>
          }
          <Button onClick={toggleColorMode}>Toggle color mode</Button>
        </div>
      </main>
    </div>
  )
}
