import { Button, useColorMode } from '@chakra-ui/react'
import Head from 'next/head'
import { Link } from '@/components'
import { useAppSelector } from '@/hooks/useAppSelector'

export default function Home() {
  const { toggleColorMode } = useColorMode()
  const { isAuth } = useAppSelector(state => state.auth)

  
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home Page</h1>
        <h2>NODE_ENV: {process.env.NODE_ENV}</h2>
        <div>
          {isAuth ?
            <>
              <Link href='/chats'>IsAuth</Link>
            </>
          :
            <>
              <Link href='/signup'>Sign Up</Link> <br />
              <Link href='/signin'>Sign In</Link>
            </>
          }
          <Button onClick={toggleColorMode}>Toggle color mode</Button>
        </div>
      </main>
    </div>
  )
}
